######################################################################
# Automatically generated by qmake (3.0) Thu Jan 12 18:37:20 2017
######################################################################

TEMPLATE = app
TARGET = once
INCLUDEPATH += . ..
CONFIG += c++11 warn_on debug
OBJECTS_DIR = tmp
MOC_DIR = tmp

# Input
HEADERS += ../once.h Sender.h Receiver.h
SOURCES += test.cpp
